aspect-build/rules_py

- py/defs.bzl
> fix: don't pass kwargs to py_venv rule

- py/private/py_binary.bzl
- py/private/utils.bzl
- py/private/venv/venv.bzl
> fix: ensure all Python toolchain files are added to runfiles

- py/private/entry.tmpl.sh
- py/private/py_binary.bzl
- py/private/utils.bzl
- py/private/venv/venv.bzl
> feat: support interpreter_path from py3_toolchain

- py/private/utils.bzl
@JesseTatasciore was right, this is a pointless check as it's already validated by bazel on the `py_runtime` rule:
```
ERROR: /private/var/tmp/_bazel_matt/b28310042610550fd4cf1ffc282c1f7a/external/host_python_autodecting_toolchain/BUILD.bazel:3:11: in py_runtime rule @host_python_autodecting_toolchain//:autodecting_python3_runtime: exactly one of the 'interpreter' or 'interpreter_path' attributes must be specified
```
> fix: remove check on missing interpreter or interpreter_path on the toolchain

- py/BUILD.bazel
- py/private/toolchain/BUILD.bazel
- py/private/toolchain/autodetecting.bzl
- py/private/toolchain/python.sh
- py/repositories.bzl
Fixes #21 
```
$ which python3
/opt/homebrew/bin/python3
$ python3 --version
Python 3.9.10
$ bazel run --override_repository rules_py=/Users/matt/Documents/workspace/rules_py ipython
INFO: Analyzed target //:ipython (26 packages loaded, 95 targets configured).
INFO: Found 1 target...
Target //:ipython up-to-date:
bazel-bin/ipython
INFO: Elapsed time: 1.458s, Critical Path: 1.33s
INFO: 3 processes: 2 internal, 1 darwin-sandbox.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
Python: /private/var/tmp/_bazel_matt/b28310042610550fd4cf1ffc282c1f7a/execroot/rules_py_example/bazel-out/darwin_arm64-fastbuild/bin/ipython.runfiles/ipython.venv/bin/python_real
version: 3.9.10 (main, Jan 15 2022, 11:40:53)
[Clang 13.0.0 (clang-1300.0.29.3)] …
```
> feat: add autodetecting toolchain compatible with rules_py venvs

- py/private/py_library.bzl
- py/tests/import-pathing/BUILD.bazel
- py/tests/import-pathing/tests.bzl
Fixes a few issues around import pathing on the `py_library` utils and adds tests.
Ensures that paths don't escape the root or are absolute, and fixes issues with relative paths that descend into a different subtree.
> fix: workspace import pathing on py_library

- py/private/py_wheel.bzl
Only take the `DefaultInfo` when there is no `PyInfo`. This stops us adding the source files from a rules_python / native py_library to the requirements file when installing wheels.
This is kinda a workaround that the upstream rules_python doesn't have a provider that can give a reference to the wheel, and we must get it from the `DefaultInfo` of a filegroup.
> fix: don't add source files to requirements files from transitive native py_library rules

- .bazelrc
I like seeing the errors rather than having to manually cat the file
> chore: show errors by default for failed tests

- py/repositories.bzl
Update to get the aarch64 arc on Linux platform
> chore: update rules_python to 0.8.1

- py/private/entry.tmpl.sh
- py/private/toolchain/autodetecting.bzl
- py/private/toolchain/python.sh
- py/private/utils.bzl
- py/tests/external-deps/expected_pathing
On MacOS (or at least what I'm running), it has some odd semantics around how `/usr/bin/python` behaves which appear to depend on the **name** of the binary itself 🙄 
If the autodetecting toolchain links `/usr/bin/python`, then the shim will call `python_real`, which in turn gets called by whatever the binary at `/usr/bin/python` is, and as `python_real` isn't a binary it can call, it decides it needs to install Xcodes command line utilities. This of course doesn't help, and the cycle continues.
Instead, link to `python3`, and only link in `python` into the venv/bin as the others were kinda extraneous anyway.
> fix: symlink to python3 instead of python_real

- py/private/venv/venv.bzl
- py/tests/external-deps/BUILD.bazel
- py/tests/external-deps/expected_pathing
- py/tests/external-deps/test_can_import_runfiles_helper.py
- py/tests/import-pathing/tests.bzl
A few imports rely on being able to reference the root of the runfiles tree as a Python module, the common case here being the `@rules_python//python/runfiles` or `@bazel_tools//tools/python/runfiles` targets that adds the runfiles helper, which ends up in `bazel_tools/tools/python/runfiles/runfiles.py` (or the rules_python equiv path), but there are no imports attrs that hint we should be adding the root to the `PYTHONPATH`.
> fix: add the runfiles root as a python package

- BUILD.bazel
- WORKSPACE
- internal_deps.bzl
- py/private/py_binary.bzl
- py/tests/containers/BUILD.bazel
- py/tests/containers/__main__.py
- py/tests/containers/py_image_test.yaml
Return a `PyInfo` provider from the `py_binary` (and, `py_test` for that matter) rules. This allows them to be plugged into the `py*_image` rules from rules_docker. 
There is a slight caveat here - if the user is using the wheel approach then the `PyInfo` provider is not sufficient in providing all the required files to put into the container. Will circle back and think about that one.
> feat: return PyInfo provider from py_binary rules

- internal_deps.bzl
- py/repositories.bzl
It's no fewer lines than inlining that function, and as a result renovate will understand our dependencies
Alternative to getting support for this pattern in renovate itself
> refactor: remove use of maybe() helper

- internal_deps.bzl
- py/repositories.bzl
This commit gets the two imports in sync and fixes the missing archive on mirror.bazel.build.
> fix: skylib download warning

- py/private/venv/venv.tmpl.sh
Cleans up all symlinks in generated venv. This needs to happen such that remote caching works properly when `--remote_download_minimal` or `--remote_download_toplevel` are used.
> Clean up all symlinks in venv

- py/private/py_pytest_main.bzl
- py/private/pytest.py.tmpl
Fix flake8 and black formatting issues in generated pytest driver by adding a no-op statement instead of an empty string. The previous version resulted in a file with 2 blank lines if chdir was undefined, resulting in the following issues being raised:
```
bazel-out/k8-fastbuild/bin/REDACTED/__test__.py:21:1: BLK100 Black would make changes.
bazel-out/k8-fastbuild/bin/REDACTED/__test__.py:21:1: W293 blank line contains whitespace
bazel-out/k8-fastbuild/bin/REDACTED/__test__.py:23:5: E303 too many blank lines (2)
```
> fix black and flake8 errors in generated pytest runner.

- .github/workflows/new_issue.yaml
- .github/workflows/new_pr.yaml
Rolling this out to all our OSS bazel rules repos to automatically tag new issues as `untriaged` and add new issues & PRs to the Aspect OSS Bazel Rules project
> chore: add workflows for new issues & PRs

- gazelle_python.yaml
- py/tests/external-deps/expected_pathing
- requirements.in
- requirements.txt
Fixes https://github.com/aspect-build/rules_py/security/dependabot/8
> chore: update django to resolve dependabot alert

- .bazelversion
Bumps the bazel version to 6.3.1
---
> chore: bump bazel version to 6.3.1

- py/private/venv/venv.bzl
- py/private/venv/venv.tmpl.sh
If an in-build interpreter is used for venv creation, then the script needs to resolve the path to the interpreter via the runfiles library.
---
**For changes visible to end-users**
- Suggested release notes are provided below:
Ensure in-build interpreters are resolved when creating venvs.
- Manual testing
> fix: use rlocation for interpreter location

- docs/rules.md
- py/defs.bzl
- py/private/py_binary.bzl
- py/private/venv/venv.bzl
- py/tests/external-deps/expected_pathing
Exposes the `py_venv` rule, which can create a Python virtual environment from a set of targets.
This allows for easier creation of environments for IDE use, as they can contain dependencies from multiple targets, such as tests.
The virtual environment that is created uses paths for first party libraries that resolve into the source tree. While this allows for a nicer user experience within the IDE, such as editing files being "live", it is less "correct" as the Bazel target may reflect a different state.
> feat: expose py_venv rule, allowing creation of virtual envs from multiple targets

- docs/rules.md
- py/private/py_pytest_main.bzl
- New feature or functionality (change which adds functionality)
Adds 2 new **optional** parameters to `py_pytest_main(...)` rule: `data` and `testonly`. These are standard arguments to the `py_library`. This change simply exposes the arguments to the `py_pytest_main` rule
closes: #189 
> Add `testonly` and `data` parameters to `py_pytest_main` rule

- docs/rules.md
- examples/pytest/BUILD.bazel
- py/private/py_pytest_main.bzl
> chore: dogfood our rules rather than rules_python

- py/private/py_binary.bzl
- py/private/venv/venv.bzl
The to_manifest_path is removed on the 2.x branch
---
> chore: use modern helper from bazel-lib

- .gitattributes
- .github/workflows/release_prep.sh
Makes it match bazelbuild/rules_proto#189
---
I made a clean git repo and verified the export-* settings work in .gitattributes
> refactor: put 'git archive' config in .gitattributes

- py/private/venv/venv.bzl
- py/tests/virtual/django/BUILD.bazel
This allows users to provide a resolution for the direct dependency they see, ensuring that the venv will be created with its dependencies installed as well.
---
The new py_binary can run successfully; without this change it couldn't import `asgiref`
> fix: install transitive wheels reachable through resolutions

- py/private/venv/venv.tmpl.sh
This is a follow-up of #226 to fix another place.
> fix: use original interpreter path as 'home' value in pyvenv.cfg

- docs/rules.md
- py/BUILD.bazel
- py/defs.bzl
- py/private/BUILD.bazel
- py/private/py_executable.bzl
- py/tests/external-deps/custom-macro/macro.bzl
- py/tests/py-binary/BUILD.bazel
- py/tests/py-binary/main_from_name.py
I don't love the semantics but it's better for us to follow our 'drop-in replacement' philosophy than explain to users how they're meant to change their code.
---
> fix: handle py_binary#main like rules_python does

- py/private/py_library.bzl
At the client where I'm installing rules_py, this absence caused a test failure in //bazel/examples/proto:test_my_service
---
Client build passes now. I can make a regression test in this repo if you like.
> fix: py_library add srcs to its runfiles

- .bazelrc
- .github/workflows/ci.yaml
- .gitignore
- MODULE.bazel
- e2e/smoke/WORKSPACE.bazel
- py/private/toolchain/tools.bzl
- py/private/toolchain/types.bzl
- py/private/toolchain/unpack/BUILD.bazel
- py/private/toolchain/venv/BUILD.bazel
- py/repositories.bzl
- py/tools/unpack_bin/BUILD.bazel
- py/tools/venv_bin/BUILD.bazel
We must take care that `rules_rust` load statements don't appear in public API packages.
> fix: move toolchain registration to different package

- Cargo.Bazel.lock
- Cargo.lock
- MODULE.bazel
- py/tools/py/Cargo.toml
#233 was mentioned as a fix for #218 but #233 includes a dependency on openssl. This dependency on openssl makes building containers on MacOS difficult as we then need to cross build openssl. I see that there was an attempt to remove the openssl dependency `rattler_installs_packages` however, `native-tls` is in the default features and is the only default feature. Disabling `default-features` removes the dependency on openssl.
> Remove openssl

- e2e/smoke/MODULE.bazel
We can be on a regular release now.
This was missed in #279
> chore: bump rules_python

- .github/workflows/ci.yaml
- .github/workflows/integrity.jq
- .github/workflows/release.yml
- .github/workflows/release_prep.sh
- tools/integrity.bzl
Demo:
https://github.com/alexeagle/rules_py/releases/tag/v0.100.8
the `rules_py-v0.100.8.tar.gz` artifact has the following content in `tools/integrity.bzl`
```
"Generated during release by release_prep.sh, using integrity.jq"
RELEASED_BINARY_INTEGRITY = {
"unpack-macos-aarch64": "f97a503e2fb2614ca27355c03bb7b743092e91efab15f5eee139aff9cb41c915",
"unpack-macos-x86_64": "6af1d8466a40d0a18b7802642a5ff477b82f9008d5fc6678113b422d2d33bed0",
"venv-macos-aarch64": "3b37f326418e4e77426b9c9a05eb958e29fd0045435624611c3571e77730612a",
"venv-macos-x86_64": "f0f8a5e9484bb2ff98e788ebea87b3e960b5745ece837e68e5d2732985a84e32",
"unpack-linux-aarch64": "48552e399a1f2ab97e62ca7fce5783b6214e284330c7555383f43acf82446636",
"unpack-linux-x86_64": "fd265552bfd236efef519f81ce783322a50d8d7ab5af5d08a713e519cedff87f" …
```
> feat: GHA release automation for rust bins

- .bazelrc
- examples/py_binary/BUILD.bazel
- examples/py_binary/say.py
- gazelle_python.yaml
- requirements.in
- requirements.txt
It seems like this issue has already been fixed, I flipped the flag for future cases. 
closes #152
> chore: flip no legacy external runfiles

- .bcr/presubmit.yml
Turn off Windows testing. It's red on BCR. We don't publish windows binaries for our Rust tools yet.
Upstreaming https://github.com/bazelbuild/bazel-central-registry/pull/1572/commits/9a64dd61504a046b76043055f5adae4c3fc67669
> chore: update presubmit.yml

- py/private/py_semantics.bzl
When a python toolchain is added directly using `py_runtime`, etc, the interpreter_version_info attribute (a dict) is required.
Prior to this change, it would fail in e.g. _py_binary_rule_impl with an error:
Error: 'dict' value has no field or method 'major'
Check this in earlier in _resolve_toolchain where we find the "interpreter_version_info" attribute, ensuring that it has all of the required dict keys.
---
Manual testing.
```
Error in fail: 
ERROR: In Bazel 7.x and later, the python toolchain py_runtime interpreter_version_info must be set to a dict with keys "major", "minor", and "micro".
`PyRuntimeInfo` requires that this field contains the static version information for the given
interpreter. This can be set via `py_runtime` when registering an interpreter toolchain, and will
done …
```
> chore: improve error message for py_runtime missing version info

- py/private/py_library.bzl
---
As a follow-up to https://github.com/aspect-build/rules_py/pull/299 , this PR enables the use of external dependencies that use workspace root relative imports.
This just expands current functionality to also cover the case where the dependency is from an external workspace.
> Fix for external deps that use repo root relative imports

- py/private/py_binary.bzl
- py/private/py_library.bzl
- py/private/py_unpacked_wheel.bzl
- py/private/py_venv.bzl
- py/tests/import-pathing/BUILD.bazel
- py/tests/internal-deps/BUILD.bazel
Switches to using `PyInfo` from rules_python, rather than relying on the builtin one from Java.
Note that this doesn't add any interoperability between the **native** `py_*` rules (java based) and the exports from rules_python. As such, using rules_python with the native java based rules and providers is no longer supported after this commit.
If we want, we could support it, but being able to consume and return both providers.
---
**For changes visible to end-users**
- Breaking change (this change will force users to change their own code or config)
- Suggested release notes are provided below:
Use `PyInfo` provider as loaded from rules_python, and drop support for dependency edges from native `py_*` rules.
> fix: use PyInfo from rules_python

- py/private/py_library.bzl
Remove the `allow_files = True` from the `deps` attr of `py_libaray` (they are inherited by `py_binary`). This allowed users to place non-existent targets into `deps`.
Closes #316
> fix: don't allow files in deps attr

- WORKSPACE
- e2e/smoke/WORKSPACE.bazel
- e2e/use_release/WORKSPACE.bazel
- py/extensions.bzl
- py/repositories.bzl
- py/toolchains.bzl
Currently, rules_py_dependencies and rules_py_toolchains are exported from the same bzl file which makes it impossible to depend on another rule and load from at the same since both macros are in the same file.  This changes this to allow adding a dependency and loading from it.
**For changes visible to end-users**
- Breaking change (this change will force users to change their own code or config)
- Relevant documentation has been updated
> refactor: split toolchains and repositories

- Cargo.Bazel.lock
- WORKSPACE
Bump rust version to 1.77.2
---
> chore: bump rust to 1.77.2

- .bcr/presubmit.yml
- e2e/use_release/minimal_download_test.sh
Because bzlmod users get a module that doesn't have a rules_rust dep
---
> fix: BCR presubmit should test the release path

- tools/integrity.bzl
Main test-release job is currently red: https://github.com/aspect-build/rules_py/actions/runs/8931817426/job/24534559732. Was broken by the last landed commit https://github.com/aspect-build/rules_py/commit/70797c49a1d2308a9eda9f8e3f3514eee397a209.
---
CI
> ci: green up main

- docs/rules.md
- py/defs.bzl
- py/private/py_library.bzl
This causes errors for one of our clients. @dizzy57 is planning to file a corresponding issue.
Fixes #368 
---
- Breaking change (forces users to change their own code or config): yes
`py_library` no longer defaults to `imports=["."]`. we recommend using longer-form import statements to import first-party libraries. You can manually restore this value on the `imports` attribute of your libraries if you still want to import them with shorthand.
> refactor: don't default imports to current folder

- .bcr/presubmit.yml
- e2e/use_release/BUILD.bazel
- e2e/use_release/__init__.py
- e2e/use_release/__main__.py
- e2e/use_release/minimal_download_test.sh
- e2e/use_release/test.py
- tools/integrity.bzl
The BCR presubmit runs `bazel test` in the `e2e/use_release` directory, and requires an actual test, else bazel fails with the "no tests found" error. This diff adds a simple test, and bumps the tested binaries to 0.7.4.
---
> chore: add smoke test to e2e/use_release

- MODULE.bazel
> fix: mark a 'testing only' python toolchain as dev_dep

- py/private/py_venv.bzl
- py/private/venv.tmpl.sh
After testing real developer workflows in vscode, this way works correctly and is much more practical.
Fixes #395
---
Try a few things in VScode:
1. in the root, run `bazel run app:app_bin.venv` and see VSCode offers to open the resulting virtual env, labels it well
2. open the app folder in the editor, then run `bazel run app_bin.venv` which also is detected
3. run `bazel run app_test.venv` and the editor offers to switch
4. open a terminal in vscode and run `python -m pytest` and the tests run correctly, meaning they should also be debuggable
> refactor: py_venv macro improved defaults for usability

- .bcr/presubmit.yml
it's red for the last couple releases, and Bazel 8 RC will come out next week so we should switch to testing that.
> chore(BCR): drop Bazel 6 testing

- MODULE.bazel
- docs/BUILD.bazel
- docs/py_image_layer.md
- py/BUILD.bazel
- py/defs.bzl
- py/private/BUILD.bazel
- py/private/py_image_layer.bzl
- py/repositories.bzl
- py/toolchains.bzl
Replaces https://github.com/aspect-build/rules_py/pull/349
Add `py_image_layer` macro for creating py container images.
I will add a test in a follow-up.
> feat: add py_image_layer

- py/tools/py/src/pth.rs
When expanding wheels via rules_pycross' `pycross_wheel_library`, the wheels end up in `bazel-out`, rather than within the runfiles tree like when consuming from rules_python. To account for this, change the delimiter to `site-packages/` given that is the actual common ancestor in the path.
This also changes to using the full paths for reporting the conflict to make it easier to see where the incoming conflict is from.
Closes #359
---
Use `site-packages/` as path delimiter when reporting venv package conflicts. …
> fix: split on site-packages path segment when reporting conflicts

- .github/workflows/ci.yaml
Runs CI on all pull requests even if they don't target `main`. This allows getting feedback on stacked diffs without having to wait for each diff in the stack to be popped.
---
None
> chore: run CI for all pull requests

- Cargo.Bazel.lock
- Cargo.lock
- Cargo.toml
- MODULE.bazel
- WORKSPACE
- e2e/repository-rule-deps/MODULE.bazel
- e2e/smoke/MODULE.bazel
- e2e/smoke/WORKSPACE.bazel
- e2e/system-interpreter/MODULE.bazel
- py/tools/py/Cargo.toml
- py/tools/py/src/interpreter.rs
- py/tools/py/src/unpack.rs
- py/tools/unpack_bin/Cargo.toml
Bumps the Rust version to 1.81.0 and updates required dependencies.
---
> chore: bump rust version to 1.81.0

- Cargo.Bazel.lock
- Cargo.lock
- Cargo.toml
- WORKSPACE
- py/private/py_binary.bzl
- py/private/py_unpacked_wheel.bzl
- py/private/py_venv.bzl
- py/private/run.tmpl.sh
- py/private/toolchain/tools.bzl
- py/private/venv.tmpl.sh
- py/tests/virtual/django/BUILD.bazel
- py/tools/pex/BUILD.bazel
- py/tools/py/BUILD.bazel
- py/tools/py/Cargo.toml
- py/tools/py/src/lib.rs
- py/tools/py/src/unpack.rs
- py/tools/py/src/venv.rs
- py/tools/unpack_bin/BUILD.bazel
- py/tools/unpack_bin/Cargo.toml
- py/tools/unpack_bin/src/main.rs
- py/tools/venv_bin/BUILD.bazel
- py/tools/venv_bin/Cargo.toml
- py/tools/venv_bin/src/main.rs
- tools/linkers/BUILD.bazel
- tools/platforms/BUILD.bazel
- tools/release/BUILD.bazel
- tools/release/defs.bzl
- tools/release/fetch.bzl
Drops the dependency on `rattler_installs_packages` in favour of the uv crates.
Note that while this works, the creates of uv do not officially support depending directly on the crates, however there is little overhead here, and is pinned to a fixed SHA.
Closes #307
Closes #344
Closes #345
Due to compilation issues under llvm, this diff also switches to musl for the toolchain binaries. We need to keep llvm for proc macros, unfortunately. 
---
Drop dependency on `rattler_installs_packages` in favour of the uv crates.
Produce statically linked toolchain binaries via musl.
> feat: drop rattler_installs_packages for uv crates

- .github/workflows/ci.yaml
It's just asserting the shape of what we download, can verify that manually still. Want to unblock 1.0 release
---
None
> chore: disable broken test

- py/private/pytest.py.tmpl
I am adding types to user_args otherwise mypy complains when running `bazel test`.
I am trying to automatically run `mypy` when building my bazel targets. I am using [rules_mypy](https://github.com/theoremlp/rules_mypy) for this. 
I am also using the `py_pytest_main` rule: 
```python
py_pytest_main(
name = "__test__",
deps = ["@pip//pytest"],
)
py_test(
name = "mytest",
size = "small",
srcs = [
"mytest.py",
":__test__",
],
main = ":__test__.py",
package_collisions = "warning",
deps = [
":__test__",
":mylib",
],
)
```
However, if I run `bazel test mytest`, mypy complains: `bazel-out/k8-fastbuild/bin/src/backend2/__test__.py:42: error: Need type annotation for "user_args" (hint: "user_args: list[<type>] = ...")  [var-annotated]`.
I haven't found a way to remove the `__test__` file from …
> Add types to file generated by __test__.py

- py/private/pytest.py.tmpl
Reverts aspect-build/rules_py#428
Revert as it's causing a failure on CI for older versions of Python.
> Revert "Add types to file generated by __test__.py"

- py/private/pytest.py.tmpl
As suggested in https://github.com/aspect-build/rules_py/pull/435#issuecomment-2482658330 a backwards compatible (< Python 3.9) type hint.
Regardless of merging this PR or not, the current 1.0.0 release is broken for < Python 3.9. Since Python 3.8 is already EOL, this is in theory valid, but I guess there are still a few people using Python 3.8 because of Ubuntu 20.04.
---
> Add backwards compatible types to file generated by __test__.py

- MODULE.bazel
- examples/pybind11/BUILD.bazel
- examples/pybind11/MODULE.bazel
- examples/pybind11/basic.cpp
- examples/pybind11/basic_test.py
Add an example for pybind11 with rules_py which is a modified version of https://github.com/pybind/pybind11_bazel/tree/master/examples/basic.
---
> example: Add example for pybind11

- .gitattributes
- docs/py_binary.md
- docs/py_library.md
- docs/py_test.md
- docs/venv.md
- docs/virtual_deps.md
- py/private/py_library.bzl
- py/private/py_venv.bzl
- py/tests/virtual/django/BUILD.bazel
Fixes a docs FIXME.
Also show how a dependency can be dropped altogether using an empty filegroup, as requested by a client.
---
> docs: document virtual_deps and resolutions

- py/private/py_binary.bzl
This mirrors the behavior of rules_python's py_binary, and other
*_binary rules. Previously any env set on the binary was baked into the
script, and therefore included if the script was run with --run_under,
or through a genrule. Now this env is passed through to
RunEnvironmentInfo so it only applies in the default cases.
> Don't bake env into binary

- .pre-commit-config.yaml
- e2e/repository-rule-deps/README.md
The pre-commit hooks are quite old in this repo. This PR run `pre-commit autoupdate`. Since the hooks are not enfored by CI, buildifier is already broken. I will create a follow up PR similar to https://github.com/bazel-contrib/bazel-lib/pull/1002 that adds it to CI and fix all errors.
> ci(pre-commit): Autoupdate

- py/defs.bzl
- py/private/py_image_layer.bzl
- py/tests/py_image_layer/asserts.bzl
See https://bazel.build/extending/macros#naming, these naming conventions are violated by this legacy macro (and thus by a symbolic macro wrapping this legacy macro)
- Searched for relevant documentation and updated as needed: yes/no
- Breaking change (forces users to change their own code or config): yes/no
- Suggested release notes appear below: yes/no
> fix: Compatibility with symbolic macros

- py/private/pytest.py.tmpl
The `junit.xml` files generated by pytest use the name `pytest` by default. For any tools that consume the xml files like IDEs or CI system UIs, this makes the output unfriendly because every test case rolls up the the same test suite named `pytest`.
The changes here add the `BAZEL_TARGET` name to the suite using standard pytest command line args.
Here is an example before and after when running the tests with and without the change in IntelliJ. The example only runs two test targets. The issue becomes more apparent as the number of targets scales up.
---
- Searched for relevant documentation and updated as needed: no
- Suggested release notes appear below: no
Run a `py_test` target that uses `py_pytest_main` and …
> pytest - add suite name to junit.xml report

- docs/py_binary.md
- docs/py_test.md
- examples/virtual_deps/BUILD.bazel
- examples/virtual_deps/README.md
- examples/virtual_deps/cowsnake/cowsay.py
- examples/virtual_deps/greet.py
- examples/virtual_deps/greet_test.py
- examples/virtual_deps/main.py
- gazelle_python.yaml
- py/defs.bzl
- py/private/virtual.bzl
- requirements.in
- requirements.txt
Closes https://github.com/aspect-build/rules_py/issues/466
- Make resolutions consistent between `py_binary` and `py_test`
- Allow a list to be passed to `from_requirements`
- Add an example of `virtual_deps` feature
---
- Suggested release notes appear below: 
> - Fix: Make resolutions consistent between `py_binary` and `py_test`
> - Feature: Allow a list to be passed to `from_requirements`
> - Docs:  Add an example of `virtual_deps` feature
- Manual testing; please provide instructions so we can reproduce: Added an example
> fix: make py_binary#resolutions and py_test#resolutions identical. 

- .github/workflows/ci.yaml
- e2e/use_release/MODULE.bazel
- e2e/use_release/minimal_download_test.sh
- tools/integrity.bzl
May be useful to assert that coverage support is working, since we have a hard time compiling rust tools under --collect_code_coverage
---
> refactor(ci): re-enable testing against prior release artifacts

- .gitignore
One of the tools, maybe `prettier` creates a `node_modules` folder locally which should be ignored.
---
no testing required
> chore: gitignore node_modules folder

- docs/py_image_layer.md
- py/private/py_image_layer.bzl
It's named `binary` rather than `py_binary`
> docs: fix example of py_image_layer

- .bcr/patches/rust_dev_dep.patch
- .github/workflows/ci.yaml
- e2e/use_release/minimal_download_test.sh
From `man patch`
```
-F max-fuzz, --fuzz max-fuzz
Sets the maximum fuzz factor.  This option only applies to
context diffs, and causes patch to ignore up to that many lines
in looking for places to install a hunk.  Note that a larger fuzz
factor increases the odds of a faulty patch.  The default fuzz
factor is 2, and it may not be set to more than the number of
lines of context in the context diff, ordinarily 3.
```
The hint was in our CI job which passes but prints 
```
Run patch --dry-run -p1 < .bcr/patches/*.patch
checking file MODULE.bazel
Hunk #1 succeeded at 45 with fuzz 2 (offset 4 lines).
Hunk #2 succeeded at 61 with fuzz 2 (offset 3 lines).
```
When Bazel or the Publish to BCR app apply the patches, they don't use the `patch` tool so they don't allow any variation in the patch …
> fix(ci): assert that patches apply exactly

- .github/workflows/ci.yaml
The GHA job for the root folder is taking 12min while all the rest are 4min. We setup Aspect Workflows recently which gives us test coverage.
Note, we'll have to adjust the branch protection to gate PRs on AW passing
> chore(ci): make it 8min faster

- .github/workflows/ci.yaml
Changes the message it writes to the GH review comment.
> chore: clarify that the coverage report isn't for the whole repo

- py/private/py_binary.bzl
Bazel is not producing combined coverage report for targets that don't define the `_lcov_merger` attribute, the `collect_coverage.sh` script just exits silently in this case: https://github.com/bazelbuild/bazel/blob/fde4b67009d377a3543a3dc8481147307bd37d36/tools/test/collect_coverage.sh#L186-L194
Since `rules_python` defines this attribute both for `py_binary` and `py_test`, we're mirroring this behavior by modifying `py_base.attrs`.
Tested by applying the patch and verifying that `bazel-out/_coverage/_coverage_report.dat` is not empty after running `bazel coverage --combined_report=lcov [target]`.
> fix(coverage): produce combined coverage report

- .github/workflows/ci.yaml
- py/private/py_binary.bzl
- py/private/pytest.py.tmpl
https://github.com/bazelbuild/bazel/issues/25118 was causing our coverage reports to fail to parse into combined report.
Related to #520 which was missing testing that the report actually worked.
fyi @dizzy57
> fix: workaround Bazel lcov parsing bug

- .github/workflows/ci.yaml
- e2e/use_release/.coveragerc
- e2e/use_release/BUILD.bazel
- e2e/use_release/src/BUILD.bazel
- py/private/pytest.py.tmpl
Issue reported here: https://github.com/aspect-build/bazel-examples/pull/404#issuecomment-2623040853
Now looks like
```
SF:src/__init__.py
DA:1,1
DA:2,1
```
Similar to https://github.com/bazelbuild/rules_python/blob/466da1d9710289bfb01061b9be7bb124132996e0/python/private/python_bootstrap_template.txt#L336-L346 
but ours is a bit more principled since we don't break the abstraction of what coveragepy happens to do with the paths.
Just `bazel coverage src:test` and inspect the .dat file
> fix: workaround absolute paths appearing in coverage data

- .github/workflows/release.yml
GitHub will force us soon:
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
March 4 14:00 UTC – 22:00 UTC
March 11 13:00 UTC – 21:00 UTC
March 18 13:00 UTC – 21:00 UTC
March 25 13:00 UTC – 21:00 UTC
Note, the only way I know to test this is to land it and 🤞🏻 a release
> chore(release): upgrade Ubuntu

- docs/py_test.md
- e2e/use_release/src/BUILD.bazel
- examples/pytest/BUILD.bazel
- examples/pytest/foo_test.py
- py/defs.bzl
- py/private/pytest.py.tmpl
Comes from https://github.com/caseyduquettesc/rules_python_pytest/pull/13 It's much easier to properly gazelle-generate a BUILD file in this shape rather than the awkward way you're forced to hold our py_pytest_main.
> feat: port pytest_test macro

- MODULE.bazel
- WORKSPACE
- examples/py_binary/BUILD.bazel
- examples/py_binary/say.py
Came up from a customer question.
---
> chore: demonstrate py_binary stamping

- py/private/py_binary.bzl
- py/private/py_venv.bzl
Bazel @ HEAD moved the bash runfiles to rules_shell. In this case
accessing just the single file was no longer valid.
> Fix bash runfiles with rules_shell

- docs/venv.md
- py/defs.bzl
- py/private/py_venv.bzl
If your venv requires runtime dependencies in the build, these
previously weren't built
> Add data to py_venv rule

- docs/py_image_layer.md
- py/private/py_image_layer.bzl
I needed to be able to change the owner of some files in the final oci image. `mtree_mutate` seemed the right way to do it, but I couldn't control the mtree while using `py_image_layer` , so this adds an `owner` option to handle the `mtree_mutate`
- Suggested release notes appear below: no
I tested by adding an `owner` attribute to an image I was generating.
I did not update any tests, but if this change is approved, I can go back and add if we think its necessary.
> Add an owner arg to py_image_layer

- .github/workflows/publish.yaml
- .github/workflows/release.yml
This includes provenance attestations for our rust binaries and the release artifact
Note, I've already disabled the Publish to BCR GH App for this repo, and added the BCR_PUBLISH_TOKEN as an org-wide secret
> chore: switch to upstream release workflow

- Cargo.Bazel.lock
- Cargo.lock
- Cargo.toml
- MODULE.bazel
- WORKSPACE
- e2e/smoke/WORKSPACE.bazel
- py/tools/venv_shim/BUILD.bazel
- py/tools/venv_shim/Cargo.toml
- py/tools/venv_shim/src/main.rs
Related to #522 and associated issues.
This PR introduces a new venv tool, what for lack of better words I'm calling the "shim".
While standard interpreters do support the use of relative paths to the interpreter in `pyvenv.cfg` -- for instance `home = ./bin/python` is legal -- we still need a `bin/python` which is portable. Existing relocatable virtual environment solutions (uv, conda) still ultimately create both an absolute path reference in `pyvenv.cfg` and usually in the `bin/python` symlink to a specific interpreter on the filesystem. UV does this statically as is standard, Conda will also do this statically with an explicit update process as part of the conda unpack.
We can't create relocatable symlinks, and we also can't dynamically correct static symlinks without continuing to …
> feat(venv): Create a relocatable venv shim

- examples/pytest/BUILD.bazel
- py/defs.bzl
Fixes https://github.com/aspect-build/rules_py/issues/461
> Fix exec_properties for py_test

- py/private/py_library.bzl
- py/tests/cc-deps/BUILD.bazel
- py/tests/cc-deps/example_library.cpp
- py/tests/cc-deps/test_smoke.py
Hi Aspect Team
This PR enables better compatibility with pybind11_bazel and makes the aspect py rules more of a drop-in replacement of the official rules_python. Please let me know if you are open to this contribution, then I can also add tests for it.
More specifically: This change is useful when using a
[pybind_extension](https://github.com/pybind/pybind11_bazel/blob/2b6082a4d9d163a52299718113fa41e4b7978db5/build_defs.bzl#L28) in the `deps` of a `py_libary` as the `pybind_extension` is just a `cc_binary` under the hood. This PR enables using it like so:
```py
load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")
load("@aspect_rules_python//python:defs.bzl", aspect_py_library="py_library")
pybind_extension(
name = "my_pybind_extension",
srcs = ["my_binding.cpp"],
) …
```
> Add CcInfo to allowed providers of py_library deps.

- e2e/use_release/minimal_download_test.sh
- py/tests/py_venv_image_layer/my_app_layers_listing.yaml
- py/tools/venv_shim/BUILD.bazel
- py/tools/venv_shim/src/main.rs
Fixes a user-visible bug present in v1.5.0 which could cause the Python shim to skip over viable interpreters and fail to resolve an appropriate one.
- Suggested release notes appear below: yes/no
The Python interpreter shim exists to inspect the `pyvenv.cfg` sentinel file which defines a virtualenv, extract the interpreter version for the virtualenv and then traverse the `$PATH` attempting to identify a viable interpreter of the required version which it will chainload.
As a reminder a venv will look something like
```
|-- .venv
|   |-- bin
|   |   |-- activate
|   |   |-- pip
|   |   |-- pip3
|   |   |-- pip3.12
|   |   |-- python <- our shim
|   | …
```
> fix(shim): Apply path canonicalization

- docs/venv.md
- py/private/py_venv/BUILD.bazel
- py/private/py_venv/entrypoint.tmpl.sh
- py/private/py_venv/py_venv.bzl
- py/tests/py_venv_image_layer/my_app_amd64_layers_listing.yaml
- py/tests/py_venv_image_layer/my_app_arm64_layers_listing.yaml
- py/tools/py/BUILD.bazel
- py/tools/py/src/activate.tmpl
- py/tools/py/src/runfiles_interpreter.tmpl
- py/tools/py/src/venv.rs
- py/tools/venv_bin/src/main.rs
Previously the `bin/activate` script relied on Bazel (specifically `bazel run`) defined envvars, or being sourced directly from the binary entrypoint. This meant that if the user created a link (eg via the venv link verb or manually) to the venv defined by a given target, sourcing that venv's activate script would fail to locate a runfiles-based interpreter. On systems where there is no appropriately versioned non-hermetic interpreter available, this meant that venvs which should run with the Bazel-managed interpreter instead failed.
The fix is to harden venv initialization so that if the `activate` script is directly used AND the runfiles preconditions are not met an effort will be made to satisfy them.
---
- Searched for relevant documentation and updated as needed: no
- Breaking change …
> fix(py_venv): Activate embedded interpreters

- py/private/pytest.py.tmpl
Disable type checking in generated code.
This fixes a regression that occurred after upgrading to the latest version of the rules.  There, our tooling started producing the following typing errors.
```
bazel-out/k8-fastbuild/bin/packages/cmk-agent-based/__test__.py:35: error: Cannot find implementation or library stub for module named "coverage"  [import-not-found]
bazel-out/k8-fastbuild/bin/packages/cmk-agent-based/__test__.py:35: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
bazel-out/k8-fastbuild/bin/packages/cmk-agent-based/__test__.py:37: error: Argument 1 to "open" has incompatible type "str | None"; expected "int | str | bytes | PathLike[str] | PathLike[bytes]"  [arg-type]
bazel-out/k8-fastbuild/bin/packages/cmk-agent-based/__test__.py:78: error: …
```
> Disable typing in `py/private/pytest.py.tmpl`

- py/private/py_venv/link.py
Reported by @jimmyt857 in testing of v1.6.0-rc0
Previously running the `examples/py_binary:py_binary.venv` target would create a link `$BUILD_WORKING_DIRECTORY/.examples+py_binary+py_binary.venv`. This behavior regressed in 1.5.0 and the link became simply `$BUILD_WORKING_DIRECTORY/.py_binary.venv`.
Restore the original behavior.
---
- Searched for relevant documentation and updated as needed: no
- Suggested release notes appear below: no
```shellsession
❯ bazel run //examples/py_binary:py_binary.venv
INFO: Analyzed target //examples/py_binary:py_binary.venv (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //examples/py_binary:py_binary.venv up-to-date: …
```
> fix(venv_link): Restore original venv name mangling

- py/tests/py_venv_image_layer/my_app_amd64_layers_listing.yaml
- py/tests/py_venv_image_layer/my_app_arm64_layers_listing.yaml
- py/tools/py/src/activate.tmpl
- py/tools/py/src/runfiles_interpreter.tmpl
- py/tools/venv_shim/src/main.rs
Identified in manual testing of v1.6.0-rc0.
Because of overly conservative removals of `realpath` in #579, an issue is exposed where `$VIRTUAL_ENV` would be an un-resolved relative path both under Bazel and more significantly once a user activates a linked venv. This isn't so bad for binaries which usually don't `chdir`, but it's a problem for shells.
Since MacOS doesn't ship a `realpath` which can be configured to ignore symlinks, we can't just `realpath` the runfiles dir or the virtualenv home. But once we've configured a Python interpreter what we can do is use `os.path.abspath`. Unlike `realpath`, `abspath` does not attempt to resolve symlink path segments. It just uses `normpath` to eliminate relative path segments. This allows us to compute an absolute path in a portable way, once …
> fix(venv): Use the interpreter to abspath

- py/private/py_venv/BUILD.bazel
- py/private/py_venv/link.py
- py/private/py_venv/test_link.py
Fixes the #593 report.
Reworks the venv linking script so that we can add tests covering munging and prevent future regressions.
---
- Searched for relevant documentation and updated as needed: yes/no
- Breaking change (forces users to change their own code or config): yes/no
Fixed a regression in the naming of virtualenv links.
> fix(venv_link): Repair venv link munging

- MODULE.bazel
- py/extensions.bzl
This patch integrates [tools_telemetry](https://github.com/aspect-build/tools_telemetry) into `rules_py`. Depending on `rules_py` will register a dependency into the telemetry system and produce a usage report when external repositories are invalidated.
`aspect_tools_telemetry` is now used for coarse grained usage tracking.
N/A.
> feat(telemetry): Integrate tools_telemetry

- docs/venv.md
- e2e/use_release/minimal_download_test.sh
- e2e/use_release/src/BUILD.bazel
- py/private/py_venv/py_venv.bzl
Fixes #598.
---
Repairs an issue which caused the `venv_name` parameter to produce errors.
- Tests added
> fix(venv_link): Correct name argument

- py/private/py_venv/BUILD.bazel
- py/private/py_venv/py_venv.bzl
- py/tests/py_venv_conflict/test_import_roots.py
- py/tests/py_venv_image_layer/my_app_amd64_layers_listing.yaml
- py/tests/py_venv_image_layer/my_app_arm64_layers_listing.yaml
- py/tools/py/src/venv.rs
- py/tools/venv_bin/src/main.rs
- py/tools/venv_shim/src/main.rs
As reported by customers, the naive but correct strategy of using copies in `py_venv_*` can lead to laughable disk usage. Some clients are reporting order 10min slowdowns and order 100GiB disk usage wasted copying inputs into binaries. We need a more scalable strategy such as symlinking.
Thankfully we can generate symlinks from tools driven by Bazel into a TreeArtifact so long as the symlinks aren't dangling. By carefully crafting relative symlinks we're able to produce a tree of links which is valid both at and after action time. When relocating a `.runfiles` tree containing such links (for instance into a OCI later tar) these links must be dereferenced but that Just Works.
While I'm at it, refactor the venv machinery to operate in terms of strategies and combinators on strategies so …
> feat(py_venv): Replace untennable copying with symlinks
