aspect-build/rules_py

py/private/venv/venv.tmpl.sh
=> fix: check for setuptools before creating symlinks

py/repositories.bzl
=> chore: update aspect_bazel_lib to 0.12.1

py/repositories.bzl
=> chore: update aspect_bazel_lib to 1.0.0

requirements.in
=> chore: have less strict testing dependency constraints

docs/py_binary.md, docs/py_library.md, docs/rules.md
Accidentally merged https://github.com/aspect-build/rules_py/pull/91 without noticing that bazel test was not run. Also, changed the branch protection to require bazel test to pass before merges.
=> fix: generated docs

py/tests/containers/BUILD.bazel
*mumbles something about transitions*
=> build: set container related targets as manual

README.md
At this point we're committing to at least keeping the project around.
=> Remove EXPERIMENTAL

gazelle_python.yaml, requirements.txt
Updates a bunch of Python dependencies.
=> chore: update Python dependencies

gazelle_python.yaml, py/repositories.bzl, py/tests/external-deps/expected_pathing
Updates the version of rules_python we depend on
=> chore(deps): bump rules_python to 0.16.1

gazelle_python.yaml, py/tests/external-deps/expected_pathing, requirements.in, requirements.txt
Bumps a number of Python dependencies.
---
=> chore: bump Python dependencies

gazelle_python.yaml, requirements.txt
Updates `sqlparse` to resolve dependobot security warning.
=> chore: update sqlparse

gazelle_python.yaml, py/private/BUILD.bazel, py/repositories.bzl, py/tests/external-deps/expected_pathing, requirements.txt
Bumps rules_python to the latest.
=> chore: update rules_python

MODULE.bazel, e2e/smoke/MODULE.bazel, py/repositories.bzl
We need Matt's upstream fix which isn't released yet
---
=> chore: upgrade rules_python near HEAD

renovate.json
=> chore: don't rebase renovate diffs

.github/workflows/ci.yaml
We don't currently work on windows.
Also update SHA of the reusable workflow to upstream HEAD rather than my PR branch
---
=> chore: green up main CI

.bazelrc, .github/workflows/ci.bazelrc, .gitignore, WORKSPACE, py/tools/unpack_bin/BUILD.bazel, py/tools/venv_bin/BUILD.bazel, third_party/com.github/bazel-contrib/toolchains_llvm/BUILD.bazel, third_party/com.github/bazel-contrib/toolchains_llvm/clang_ldd.patch, tools/release/BUILD.bazel, tools/release/copy_release_artifacts.sh, tools/release/defs.bzl, tools/release/fetch.bzl
Adds release infra for the rust binaries.
---
=> chore: add release rules for binaries

py/repositories.bzl
#1671 is already in the latest release
---
=> Update rules_python dependency

tools/release/defs.bzl
```
bazel build py/tools/unpack_bin:linux
Target //py/tools/unpack_bin:linux up-to-date:
bazel-bin/py/tools/unpack_bin/unpack-aarch64-unknown-linux-gnu
bazel-bin/py/tools/unpack_bin/unpack-aarch64-unknown-linux-gnu.sha256
bazel-bin/py/tools/unpack_bin/unpack-x86_64-unknown-linux-gnu
bazel-bin/py/tools/unpack_bin/unpack-x86_64-unknown-linux-gnu.sha256
```
=> chore: rename release artifacts to match rust convention

README.md
fixes #284
---
- Documentation (updates to documentation or READMEs)
None
=> Add gazelle config note

renovate.json
Copied this setting from https://github.com/bazel-contrib/rules-template/blob/main/renovate.json
=> renovate: don't update minimum bounds in MODULE.bazel

examples/uv_pip_compile/MODULE.bazel
=> example: Bump versions in uv example

.github/workflows/release.yml
=> chore(release): no longer creating prereleases

py/private/py_pex_binary.bzl
Adds the missing `_interpreter_version_flag` attr to the pex binary rule that allows it to resolve the correct Python toolchain in older versions of bazel.
---
- Suggested release notes appear below:
Ensure `py_pex_binary` can locate the Python version on the toolchain correctly on older bazel versions.
Run test suite with bazel 6.5.0
=> fix: add missing python version flag attr to pex

py/private/py_image_layer.bzl
- Searched for relevant documentation and updated as needed: yes 
- Suggested release notes appear below: no
- Manual testing; please provide instructions so we can reproduce: tested with a client repository
=> fix: include default layer groups.

.bazelversion
=> chore: bump bazel to 7.4.0

.github/workflows/ci.yaml
=> chore: test on Bazel 8 rather than Bazel 6

examples/pytest/BUILD.bazel, py/private/py_binary.bzl
Fixes https://github.com/aspect-build/rules_py/issues/483
=> Fix py_test with nested target name

.bcr/presubmit.yml, .github/workflows/ci.yaml
Picks up https://github.com/bazel-contrib/.github/pull/25
Also test Bazel 8 on BCR presubmit.
---
=> chore: test on Bazel 8.0.0

.aspect/workflows/config.yaml
Set up an Aspect Workflows pipeline to build rules_py.
---
Yeet
=> chore: build on aspect workflows

.bcr/metadata.template.json
Allows them to approve BCR PRs
=> chore: add missing maintainers

tools/release/BUILD.bazel
```shellsession
❯ DEST=$(realpath artifacts/) bazel run //tools/release:copy_release_artifacts
INFO: Analyzed target //tools/release:copy_release_artifacts (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools/release:copy_release_artifacts up-to-date:
bazel-bin/tools/release/copy_release_artifacts
INFO: Elapsed time: 0.782s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tools/release/copy_release_artifacts aspect_rules_py/py/tools/unpack_bin/unpack-aarch64-apple-darwin aspect_rules_py/py/tools/unpack_bin/unpack-aarch64-apple-darwin.sha256 aspect_rules_py/py/tools/unpack_bin/unpack-x86_64-apple-darwin aspect_rules_py/py/tools/unpack_bin/unpack-x86_64-apple-darwin.sha256 …
```
=> chore(release): Add shim tool

.github/workflows/publish.yaml
Pick up fix for authorship of PRs
=> chore(deps): upgrade publish-to-bcr

renovate.json
For @thesayyn; kill off #57 so it stops showing up in our weekly triage review.
---
N/A.
=> Turn off the dashboard issue

.pre-commit-config.yaml
Follow up from #583, start automating updating the manifest so we can automate more merges.
---
N/A.
=> tweak(pre-commit): Automate manifest updates

README.md
=> Add language regarding telemetry to the README
